name: Deploy my-awesome-app-jbp on AWS EB using Dockerfile

env:
  APP_NAME: my-awesome-app-jbp
  AWS_REGION: us-east-1
  AWS_PLATFORM: Docker
  PIPELINE_ID: $GITHUB_RUN_ID-$GITHUB_RUN_NUMBER

on:
  workflow_dispatch:
  
jobs:
  deploy_aws:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials and version label
        uses: aws-actions/configure-aws-credential@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Version Label
        run: |
          echo "aws_version_label=${{env.APP_NAME}}-${{env.PIPELINE_ID}}" >> $GITHUB_ENV

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ env.APP_NAME }}
          environment_name: myawesomeappjbp-env
          version_label: ${{ env.aws_version_label }}
          region: ${{ env.AWS_REGION }}
          deployment_package: docker-compose.yml
